### ISSUE TITLE
long closing

### ISSUE THREAD

**Issue by sokolking** [Toxa2033/ScaleAndSwipeDismissImageView#1]
Thank for good lib.
But i have throuble.
When i swap up or down, i'm await 1-3 seconds for apply invoke method
![image](https://user-images.githubusercontent.com/13314954/63782711-7874b280-c8f4-11e9-93e8-081545877441.png)

**Comment by Toxa2033** [comment]
@sokolking Thx for feedback. Fixed in v0.7
